# Generated by Django 4.2 on 2023-04-16 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200, verbose_name='book author')),
                ('biography', models.TextField(verbose_name='biography')),
            ],
        ),
        migrations.CreateModel(
            name='BookPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=200, verbose_name='publisher name')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='about publisher')),
            ],
        ),
        migrations.CreateModel(
            name='BookTranslator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translator_name', models.CharField(max_length=200, verbose_name='translator name')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(verbose_name='book subject')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200, verbose_name='book name')),
                ('publication_year', models.PositiveIntegerField(verbose_name='publication year')),
                ('book_introduction', models.TextField(verbose_name='book introduction')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='book description')),
                ('book_price', models.PositiveIntegerField(verbose_name='book price')),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('available', 'Available'), ('not available', 'Not Available')], max_length=13, verbose_name='status')),
                ('active', models.BooleanField(default=True, verbose_name='active status')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='bookstore.bookauthor', verbose_name='book author')),
                ('book_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishers', to='bookstore.bookpublisher', verbose_name='publisher name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='book owner')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='bookstore.subject', verbose_name='book subject')),
            ],
        ),
    ]
