# Generated by Django 4.2 on 2023-04-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_alter_bookauthor_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='short description'),
        ),
    ]
