# Generated by Django 4.2 on 2023-04-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_alter_book_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_pages',
            field=models.PositiveIntegerField(blank=True, default=12, verbose_name='number of pages'),
            preserve_default=False,
        ),
    ]
