# Generated by Django 4.2 on 2023-04-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_book_book_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_pages',
            field=models.PositiveIntegerField(verbose_name='number of pages'),
        ),
    ]
