# Generated by Django 4.2 on 2023-04-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_alter_book_book_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='bookauthor',
            options={'verbose_name_plural': 'BookAuthors'},
        ),
        migrations.AlterModelOptions(
            name='bookpublisher',
            options={'verbose_name_plural': 'BookPublishers'},
        ),
        migrations.AlterModelOptions(
            name='booktranslator',
            options={'verbose_name_plural': 'BookTranslators'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': 'Subjects'},
        ),
        migrations.AddField(
            model_name='book',
            name='book_translator',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='translator', to='bookstore.booktranslator', verbose_name='book translator'),
            preserve_default=False,
        ),
    ]
