# Generated by Django 4.2 on 2023-04-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_alter_book_options_alter_bookauthor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='subject',
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ManyToManyField(related_name='subjects', to='bookstore.subject', verbose_name='book subject'),
        ),
    ]
