# Generated by Django 4.2 on 2023-04-25 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_remove_book_subject_book_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='subject',
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='bookstore.subject', verbose_name='book subject'),
            preserve_default=False,
        ),
    ]
