# Generated by Django 4.2 on 2023-04-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_remove_book_subject_book_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='author_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='book author'),
        ),
        migrations.AlterField(
            model_name='bookpublisher',
            name='publisher_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='publisher name'),
        ),
        migrations.AlterField(
            model_name='booktranslator',
            name='translator_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='translator name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(unique=True, verbose_name='book subject'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('book_name', 'book_author', 'book_translator', 'book_publisher')},
        ),
    ]
