# Generated by Django 4.2 on 2023-04-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_alter_bookauthor_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, upload_to='book_cover/', verbose_name='book cover'),
        ),
        migrations.AddField(
            model_name='bookauthor',
            name='author_image',
            field=models.ImageField(blank=True, upload_to='author_image/', verbose_name='author image'),
        ),
    ]
