# Generated by Django 4.2 on 2023-04-28 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_book_book_cover_bookauthor_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translator', to='bookstore.booktranslator', verbose_name='book translator'),
        ),
    ]
