# Generated by Django 4.2 on 2023-04-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_alter_book_book_translator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_cover',
        ),
    ]
