# Generated by Django 4.2 on 2023-04-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_remove_book_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='book image/', verbose_name='book image'),
        ),
    ]
