# Generated by Django 4.2 on 2023-05-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0014_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comments'},
        ),
    ]
